version: '3'

services:
  cakada_fe:
    container_name: cakada_fe
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cakada_fe
    restart: always
    networks:
      - public
      - scoobydoo
networks:
  scoobydoo:
    external: true
  public:
    external: true
